version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - '9229:9229'
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - mongo
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: user-service
    ports:
      - '27017:27017'
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongodb_data_container:/data/db
networks:
  webnet:
volumes:
  mongodb_data_container:
